---
version: '3.5'
services:
  deploy:
    image: ruby:3.0.0
    working_dir: /opt/project
    volumes:
      - ${PROJECT_DIR}/api-gw:/opt/project/api-gw
      - ${PROJECT_DIR}/assets:/opt/project/assets
      - ${PROJECT_DIR}/src:/opt/project/src
      - ${PROJECT_DIR}/api-spec:/opt/project/api-spec
    entrypoint: /opt/project/api-gw/deploy-api-gw.sh
    container_name: bitz-setup
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_REGION: $AWS_REGION
      PATH: $PATH
      ENV: $ENV
      COMPANY: $COMPANY
      CONFIG_FILE: $CONFIG_FILE
      APIGW_WEBACL_ARN: $APIGW_WEBACL_ARN
